### ISSUE TITLE
How to create NEO wallet address from 12 mnemonic code ?

### ISSUE THREAD

**Issue by badboy-tian** [O3Labs/neo-utils#11]
HI, How to create NEO wallet address from 12 mnemonic code ?

example:
```
bread remove focus foster oven uphold profit wealth replace senior play city
```

**Comment by saltyskip** [comment]
This functionality is not native to the NEO platform, it would need to be proposed in a NEP or NEO Enhancement proposal. 

https://github.com/neo-project/proposals

Here is the corresponding bitcoin proposal which describes the behavior you are referring to. 

https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

You could do the same system in NEO, but it is not a standard proposal. One can propose in the NEO github
