### ISSUE TITLE
Cannot send NEO use SendNativeAssetRawTransaction, send GAS ok

### ISSUE THREAD

**Issue by guotie** [O3Labs/neo-utils#31]
the same code, cannot send NEO, but can send GAS.

when send rpc, the rpc return false

**Comment by apisit** [comment]
are you using Testnet or Mainnet? typically the reason that a node returns false is the data returns from UTXO api is incorrect.

**Comment by guotie** [comment]
I use Testnet.

I'm sure the UTXO is correct.

**Comment by guotie** [comment]
solved. send NEO must be integer
