### ISSUE TITLE
Getting unspent/UTXO in a decentralized way

### ISSUE THREAD

**Issue by 26000** [O3Labs/neo-utils#33]
Is there a way to get unspent/UTXO data without API calls? I don't want to depend on it. Or is there the API server code so that I could copy UTXO generation from there?

Could you possibly also link to NEO API docs regarding unspent? I couldn't find it anywhere...

**Comment by saltyskip** [comment]
You'd have to run your own full node in this case. There is no way to query UTXO data directly from a node on the network via RPC

**Comment by 26000** [comment]
Oh. Thanks a lot, @saltyskip ! So I'll use the API if there's no way to do it easily...
