### ISSUE TITLE
How build framework supporting Mac Catalyst

### ISSUE THREAD

**Issue by damiandizeo** [O3Labs/neo-utils#51]
I need this framework with Bitcode Enabled and support for Mac Catalyst (architecture x86_64 )

**Comment by WyattMufson** [comment]
You can use it with https://github.com/RyuGames/neovm-utils through Cocoa Pods or just download it out of the repo.

**Comment by WyattMufson** [comment]
Oh, it won't work for macOS architecture, but it'll have bitcode support

**Comment by damiandizeo** [comment]
trying to re-compile the library adding catalyst architecture In x/mobile/cmd/gomobile/env.go. Added a new case "catalyst" for function envInit which looks like this:

```
case "catalyst":
    clang, cflags, err = envClang('macosx')
    cflags += " -target x86_64-apple-ios13.0-macabi"
```

but when I install 

> go get github.com/o3labs/neo-utils/neoutils

 or build it, I get this error

> .go/src/github.com/o3labs/ont-mobile/ontmobile/oid.go:69:10: tx.Serialize undefined (type *"github.com/ontio/ontology/core/types".Transaction has no field or method Serialize)
> .go/src/github.com/o3labs/ont-mobile/ontmobile/oid.go:98:10: tx.Serialize undefined (type *"github.com/ontio/ontology/core/types".Transaction has no field or method Serialize)
> .go/src/github.com/o3labs/ont-mobile/ontmobile/transactions.go:102:15: immutTx.Serialize undefined (type *"github.com/ontio/ontology/core/types".Transaction has no field or method Serialize)
> .go/src/github.com/o3labs/ont-mobile/ontmobile/transactions.go:161:13: undefined: "github.com/ontio/ontology/core/types".Invoke
> .go/src/github.com/o3labs/ont-mobile/ontmobile/wallet.go:188:13: undefined: "github.com/ontio/ontology/core/types".Invoke
> .go/src/github.com/o3labs/ont-mobile/ontmobile/wallet.go:209:15: immutTx.Serialize undefined (type *"github.com/ontio/ontology/core/types".Transaction has no field or method Serialize)
> .go/src/github.com/o3labs/ont-mobile/ontmobile/wallet.go:305:13: undefined: "github.com/ontio/ontology/core/types".Invoke
> .go/src/github.com/o3labs/ont-mobile/ontmobile/wallet.go:325:15: immutTx.Serialize undefined (type *"github.com/ontio/ontology/core/types".Transaction has no field or method Serialize)

**Comment by WyattMufson** [comment]
@damiandizeo fyi this repo is not actively maintained

**Comment by damiandizeo** [comment]
Close this issue because was able to re compile the framework and added support for Mac catalyst .

You can find it here [damiandizeo/neoutils-framework](https://github.com/damiandizeo/neoutils-framework)
