### ISSUE TITLE
Error: go get github.com/o3labs/neo-utils/neoutils

### ISSUE THREAD

**Issue by AlleniCode** [O3Labs/neo-utils#9]
package golang.org/x/crypto/ripemd160: unrecognized import path "golang.org/x/crypto/ripemd160" (https fetch: Get https://golang.org/x/crypto/ripemd160?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by apisit** [comment]
Please try `go get golang.org/x/crypto/ripemd160`

**Comment by SephirothLT** [comment]
@apisit  it doesn't work  ,  Need  I use Proxy Software?

**Comment by apisit** [comment]
@SephirothLT  are you in China? 
You can try this instead. https://github.com/golang/crypto
